sudo: false

language: go

env:
  global:
    branch: master

install:
  - go get -v github.com/golib/assert

jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    # - stage: go1.6
    #   go: 1.6
    #   script:
    #     - go test -v -race

    - stage: 1.7
      go: 1.7
      script:
        - go test -v -race

    - stage: go1.11
      go: 1.11
      script:
        - go test -v -race

    - stage: latest
      go: latest
      script:
        - go test -v -race
